name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
    - name: Build server 
      run: go build server -o backend
